import { getDb } from "../api/queries/connection";
import { categories, products, feedback, communityPosts, users } from "./schema";
import { hash } from "bcryptjs";

async function seed() {
  const db = getDb();

  const adminPassword = await hash("admin123", 12);
  await db.insert(users).values({
    name: "Admin",
    email: "admin@nexus.local",
    password: adminPassword,
    authType: "local",
    role: "admin",
  });

  console.log("Admin user seeded (admin@nexus.local / admin123)");

  // Seed categories
  const cats = await db.insert(categories).values([
    { name: "E-Books", slug: "ebooks", description: "Digital books and guides", icon: "BookOpen" },
    { name: "Online Courses", slug: "courses", description: "Video courses and tutorials", icon: "PlayCircle" },
    { name: "Templates", slug: "templates", description: "Website and design templates", icon: "Layout" },
    { name: "Software", slug: "software", description: "Desktop and web applications", icon: "Monitor" },
    { name: "Graphics", slug: "graphics", description: "3D models, icons, and illustrations", icon: "Palette" },
    { name: "Audio", slug: "audio", description: "Music, sound effects, and plugins", icon: "Music" },
    { name: "Mobile Apps", slug: "mobile-apps", description: "iOS and Android applications", icon: "Smartphone" },
    { name: "SaaS Tools", slug: "saas-tools", description: "Cloud-based business tools", icon: "Cloud" },
  ]);

  console.log("Categories seeded");

  // Seed products
  await db.insert(products).values([
    {
      title: "Analytics Pro Dashboard",
      slug: "analytics-pro-dashboard",
      description: "A comprehensive analytics dashboard template with real-time data visualization, customizable widgets, and dark mode support. Built with React, TypeScript, and D3.js. Includes 50+ chart types, export capabilities, and responsive design.",
      shortDesc: "Professional analytics dashboard with 50+ chart types",
      price: "79.00",
      categoryId: 1,
      image: "/images/product-dashboard.jpg",
      fileSize: "25 MB",
      fileType: "ZIP",
      rating: "4.8",
      reviewCount: 124,
      salesCount: 892,
      tags: ["react", "dashboard", "analytics", "typescript"],
      isFeatured: true,
      licenseType: "Commercial",
      version: "2.1.0",
      requirements: "React 18+, Node.js 16+",
    },
    {
      title: "The Complete React Mastery Guide",
      slug: "complete-react-mastery",
      description: "Master React from fundamentals to advanced patterns. This 800-page comprehensive guide covers hooks, context, performance optimization, testing, and server components. Includes 50+ real-world projects and exercises.",
      shortDesc: "800-page guide to mastering React development",
      price: "49.00",
      categoryId: 1,
      image: "/images/product-ebook.jpg",
      fileSize: "15 MB",
      fileType: "PDF",
      rating: "4.9",
      reviewCount: 312,
      salesCount: 2450,
      tags: ["react", "javascript", "frontend", "guide"],
      isFeatured: true,
      licenseType: "Personal",
      version: "3.0",
    },
    {
      title: "Nexus Design System",
      slug: "nexus-design-system",
      description: "A complete design system with 500+ components, tokens, and patterns. Figma files included. Supports light and dark themes with full accessibility compliance. Perfect for enterprise applications.",
      shortDesc: "500+ component design system with Figma files",
      price: "129.00",
      categoryId: 2,
      image: "/images/product-templates.jpg",
      fileSize: "180 MB",
      fileType: "ZIP",
      rating: "4.7",
      reviewCount: 89,
      salesCount: 567,
      tags: ["design-system", "figma", "ui-kit", "components"],
      isFeatured: true,
      licenseType: "Commercial",
      version: "1.5",
    },
    {
      title: "Advanced Data Science Bootcamp",
      slug: "data-science-bootcamp",
      description: "12-week intensive data science course covering Python, machine learning, deep learning, and MLOps. Includes 80+ hours of video content, Jupyter notebooks, and a capstone project. Certificate of completion included.",
      shortDesc: "12-week data science course with ML and deep learning",
      price: "199.00",
      categoryId: 2,
      image: "/images/product-course.jpg",
      fileSize: "N/A",
      fileType: "MP4",
      rating: "4.9",
      reviewCount: 456,
      salesCount: 1890,
      tags: ["python", "machine-learning", "data-science", "course"],
      isFeatured: true,
      licenseType: "Personal",
      version: "2024 Edition",
    },
    {
      title: "Eclipse WordPress Theme",
      slug: "eclipse-wordpress-theme",
      description: "A premium dark-themed WordPress theme for creatives and agencies. Features include custom page builder, WooCommerce support, 20+ pre-built layouts, and blazing fast performance with 95+ PageSpeed score.",
      shortDesc: "Premium dark WordPress theme for creatives",
      price: "59.00",
      categoryId: 2,
      image: "/images/product-theme.jpg",
      fileSize: "45 MB",
      fileType: "ZIP",
      rating: "4.6",
      reviewCount: 178,
      salesCount: 1203,
      tags: ["wordpress", "theme", "dark", "creative"],
      isFeatured: false,
      licenseType: "Commercial",
      version: "4.2.1",
      requirements: "WordPress 6.0+, PHP 8.0+",
    },
    {
      title: "AudioForge Pro Plugin Suite",
      slug: "audioforge-pro",
      description: "Professional audio production plugin suite with 15 effects including EQ, compression, reverb, and mastering tools. VST3, AU, and AAX formats. Low-latency processing with GPU acceleration.",
      shortDesc: "15 professional audio effects with GPU acceleration",
      price: "149.00",
      categoryId: 5,
      image: "/images/product-audio.jpg",
      fileSize: "320 MB",
      fileType: "ZIP",
      rating: "4.8",
      reviewCount: 67,
      salesCount: 445,
      tags: ["audio", "vst", "music-production", "plugins"],
      isFeatured: false,
      licenseType: "Commercial",
      version: "3.5",
      requirements: "macOS 12+ or Windows 10+",
    },
    {
      title: "PolyVerse 3D Asset Pack",
      slug: "polyverse-3d-assets",
      description: "200+ low-poly 3D models optimized for games and VR. Includes characters, environments, vehicles, and props. All models are UV-mapped and include textures in 4K resolution. Compatible with Unity, Unreal, and Blender.",
      shortDesc: "200+ low-poly 3D models for games and VR",
      price: "89.00",
      categoryId: 4,
      image: "/images/product-3d.jpg",
      fileSize: "2.1 GB",
      fileType: "ZIP",
      rating: "4.7",
      reviewCount: 95,
      salesCount: 678,
      tags: ["3d", "unity", "unreal", "game-assets"],
      isFeatured: false,
      licenseType: "Commercial",
      version: "2.0",
    },
    {
      title: "PhotoMaster AI Plugin",
      slug: "photomaster-ai",
      description: "AI-powered photo editing plugin for Photoshop and Lightroom. Features one-click enhancement, background removal, style transfer, and batch processing. Requires internet connection for AI processing.",
      shortDesc: "AI photo editing with one-click enhancement",
      price: "69.00",
      categoryId: 3,
      image: "/images/product-plugin.jpg",
      fileSize: "150 MB",
      fileType: "ZIP",
      rating: "4.5",
      reviewCount: 234,
      salesCount: 1567,
      tags: ["photoshop", "ai", "photo-editing", "plugin"],
      isFeatured: false,
      licenseType: "Commercial",
      version: "1.8",
      requirements: "Photoshop CC 2022+",
    },
    {
      title: "SocialFit React Native App",
      slug: "socialfit-react-native",
      description: "Full-featured fitness social app built with React Native. Features workout tracking, social sharing, leaderboards, and in-app purchases. Includes complete backend integration with Firebase.",
      shortDesc: "Fitness social app with workout tracking",
      price: "99.00",
      categoryId: 6,
      image: "/images/product-app.jpg",
      fileSize: "85 MB",
      fileType: "ZIP",
      rating: "4.6",
      reviewCount: 145,
      salesCount: 934,
      tags: ["react-native", "mobile", "fitness", "firebase"],
      isFeatured: false,
      licenseType: "Commercial",
      version: "2.3",
      requirements: "React Native 0.72+, Expo SDK 49+",
    },
    {
      title: "IconCraft Pro Pack",
      slug: "iconcraft-pro-pack",
      description: "5000+ premium vector icons in 5 styles: line, solid, duo-tone, gradient, and outlined. Covers 50+ categories from business to technology. Includes Figma, Sketch, and SVG formats with variable font support.",
      shortDesc: "5000+ vector icons in 5 styles",
      price: "39.00",
      categoryId: 4,
      image: "/images/product-icons.jpg",
      fileSize: "120 MB",
      fileType: "ZIP",
      rating: "4.8",
      reviewCount: 412,
      salesCount: 3456,
      tags: ["icons", "vector", "svg", "figma"],
      isFeatured: false,
      licenseType: "Commercial",
      version: "4.0",
    },
    {
      title: "SaaS Launchpad Starter Kit",
      slug: "saas-launchpad",
      description: "Everything you need to launch a SaaS in weeks. Includes authentication, billing, team management, admin dashboard, and landing pages. Built with Next.js, Stripe, Prisma, and Tailwind CSS.",
      shortDesc: "Complete SaaS boilerplate with auth and billing",
      price: "249.00",
      categoryId: 7,
      image: "/images/product-saas.jpg",
      fileSize: "45 MB",
      fileType: "ZIP",
      rating: "4.9",
      reviewCount: 198,
      salesCount: 1234,
      tags: ["nextjs", "saas", "stripe", "boilerplate"],
      isFeatured: true,
      licenseType: "Commercial",
      version: "3.2",
      requirements: "Next.js 14+, Node.js 18+",
    },
  ]);

  console.log("Products seeded");

  // Seed feedback
  await db.insert(feedback).values([
    { name: "Sarah Chen", email: "sarah@design.co", message: "NEXUS completely transformed my workflow. The quality of templates here is unmatched. Found my go-to design system in minutes.", rating: 5, isPublic: true },
    { name: "Marcus Johnson", email: "marcus@dev.io", message: "The SaaS Launchpad saved me 3 months of development. Customer support is incredibly responsive too. Highly recommend!", rating: 5, isPublic: true },
    { name: "Elena Rodriguez", email: "elena@audio.fm", message: "AudioForge Pro is a game-changer for my mixing workflow. The GPU acceleration makes a huge difference on large projects.", rating: 4, isPublic: true },
    { name: "James Park", email: "james@startup.xyz", message: "Great selection of products but I wish there were more free previews available. Still, the purchase experience is seamless.", rating: 4, isPublic: true },
    { name: "Aisha Patel", email: "aisha@code.in", message: "The React Mastery Guide is the best investment I made this year. Clear explanations and practical projects. Worth every penny!", rating: 5, isPublic: true },
    { name: "David Kim", email: "david@3d.studio", message: "PolyVerse assets are incredibly optimized. My game runs smoother now and the art style is cohesive. Will buy more packs.", rating: 5, isPublic: true },
    { name: "Olivia Thompson", email: "olivia@photo.art", message: "PhotoMaster AI speeds up my editing by 10x. The background removal is almost perfect every time. Love it!", rating: 5, isPublic: true },
    { name: "Liam Wilson", email: "liam@mobile.dev", message: "SocialFit app template got my fitness startup MVP running in 2 weeks. Clean code structure and great documentation.", rating: 4, isPublic: true },
  ]);

  console.log("Feedback seeded");

  // Seed community posts
  await db.insert(communityPosts).values([
    { title: "Best practices for selling digital products?", content: "I've been creating design resources for a while and want to start selling on NEXUS. What are some tips for pricing, marketing, and building an audience? Any successful creators willing to share their journey?", userId: 1, category: "question", tags: ["selling", "tips", "marketing"], upvotes: 24, views: 342 },
    { title: "Showcase: My new dark UI kit", content: "Just launched my latest UI kit with 300+ components. Would love to get feedback from the community. Check it out and let me know what you think!", userId: 1, category: "showcase", tags: ["ui-kit", "showcase", "feedback"], upvotes: 56, views: 891 },
    { title: "React 19 Server Components - What changed?", content: "With the recent React 19 release, there are significant changes to how server components work. Let's discuss the implications for template creators and how we should adapt our products.", userId: 1, category: "discussion", tags: ["react", "server-components", "discussion"], upvotes: 38, views: 567 },
    { title: "Pricing strategy for premium audio plugins", content: "I'm developing a suite of audio effects and wondering about pricing. Should I go with a one-time purchase or subscription model? What do you think works better for audio tools?", userId: 1, category: "question", tags: ["pricing", "audio", "plugins"], upvotes: 15, views: 234 },
    { title: "The future of AI-generated assets", content: "AI is transforming how digital assets are created. How do you think this will impact the marketplace? Will handmade assets become more valuable or will AI-generated content dominate?", userId: 1, category: "discussion", tags: ["ai", "future", "discussion"], upvotes: 72, views: 1234 },
  ]);

  console.log("Community posts seeded");

  console.log("Seed complete!");
}

seed().catch(console.error);
